### ISSUE TITLE
Update to 4.0.x Version?

### ISSUE THREAD

**Issue by virgofx** [iuscommunity-pkg/php72u-pecl-redis#1]
Request to update the latest phpredis version (Currently 4.0.1)

**Comment by carlwgeorge** [comment]
We've been tracking this new upstream version, but have not yet decided the best way to proceed.  The [pecl release notes for 4.0.0](https://pecl.php.net/package-info.php?package=redis&version=4.0.0) indicate that version 4.0.0 includes breaking API changes.  The upstream developers provided some [additional info about those breaking changes](https://github.com/phpredis/phpredis/issues/1333).  They indicated in that issue that they intend to provide 3.x.x update for critical issues.  IUS doesn't typically have to deal with this in our primary packages (phpXXu, pythonXXu, etc.) because they are pinned to an upstream branch, so breaking changes should only happen when you switch packages, not within the same package.  The pecl redis module is different because we only build one version of it, but build it against multiple PHP versions.  There are a few possible ways to proceed.

* Keep all our pecl redis packages (php56u-pecl-redis, php70u-pecl-redis, php71u-pecl-redis, and php72u-pecl-redis) on 3.x.x, and after PHP 7.3 is released create php73u-pecl-redis at the current 4.x.x version.  This is the most conservative approach.
* Update only php72u-pecl-redis to 4.x.x and leave the rest on 3.x.x.  Typically our newest packages have the least usage, so this would have minimal negative impact, while allowing users an option to get to version 4.x.x.
* Update all our pecl redis packages to 4.x.x, and let users deal with whatever breakage is involved.  IUS stands for **I**nline with **U**pstream **S**table, and users are responsible for testing packages updates with their own infrastructure/code.
* Create new phpXXu-pecl-redis4 packages to maintain along with the existing packages.  This solution would bring about a whole slew of other issues to sort out such as:  Should phpXXu-pecl-redis4 provide phpXXu-pecl-redis?  Should it eventually obsolete it?  The packages would have to conflict, but will that cause dependency resolution issues for things that require it?

Please review the [upstream issue](https://github.com/phpredis/phpredis/issues/1333) and let me know your thoughts on this matter.

**Comment by virgofx** [comment]
I'm very familiar with the upstream issue and haven't commented on it.... In terms of breaking things ... it's VERY small -- pretty much exceptions in connect() and changes to return type for EXISTS and a few other very small things.

That being said, I appreciate the well thought out responses. I would vote in favor of #3 and #2 as being the best way forward. As mentioned, #4 will bring about a slew of new issues and probably problematic. I would argue that #2 would be the slightly more conservative version of #3 (even though I'm a fan up upgrading and letting users be compatible with the latest stable). 

So my vote is #3, then at a bare minimum #2.  Curious as to any other thoughts?

**Comment by virgofx** [comment]
Just wanted to check one of the most popular PPAs on the other side of not RHEL -- Ondřej Surý's PPA handles like 90% for all DEB/Ubuntu installs. 

They're already at 4.0.0 for all versions. He's usually pretty good with updates but 4.0.1 is new <6 days so figure it will be updated soon.

https://launchpad.net/~ondrej/+archive/ubuntu/php?field.series_filter=xenial

So that would be another +1 for #3

**Comment by Xon** [comment]
v4.1.x is now out as well

**Comment by carlwgeorge** [comment]
Sorry this fell off my radar.  PHP 7.3 is due to be released in December.  At this point, does it make the most sense to just wait and build php73-pecl-redis with 4.x.x, and leave the rest of the packages on 3.x.x?

**Comment by carlwgeorge** [comment]
[php73-pecl-redis](https://github.com/iusrepo/php73-pecl-redis) is out now using 4.x.x.
